### ISSUE TITLE
TLS not working.

### ISSUE THREAD

**Issue by yuroyami** [yuroyami/syncplay-mobile#6]
The TLS (Transport Layer Security) connection is not getting established. As a consequence, Syncplay now connects to the servers via a bare unprotected TCP/IP socket.

For many people, this is neither a priority nor an issue. But most of us prefer a secured connection over TLS/SSL if possible, which is one of the major features for Desktop's Syncplay.

This will be fixed asap.

**Comment by Et0h** [comment]
Syncplay uses [Opportunistic TLS](https://en.wikipedia.org/wiki/Opportunistic_TLS).

In my understanding the way it works from the Syncplay client's perspective is as follows:
* Syncplay client connects to the server and sends the message {"TLS": {"startTLS": "send"}} using plaintext.
* If TLS is supported then server responds with {"TLS": {"startTLS": "true"}} using plaintext.
* Once the startTLS: true message is received by the client, the Syncplay client will actually try start the TLS connection. The client will wait until that has happened before proceeding with the 'hello' messages
* Otherwise server responds {"TLS": {"startTLS": "false"}} and Syncplay just says TLS is not supported and sends the hello messages.
* If the Syncplay server is 1.6.3 or below then it would respond with an error message when it gets the starTLS message and terminate the connection. In this case, Syncplay client reconnects and skips asking if the server supports TLS and just sends the hello message in plaintext . Syncplay 1.6.4 with TLS support was released in June 2019 so you might not need to handle this edge case, but that's the expected behaviour.

**Comment by chromaticnoob** [comment]
@Et0h The issue I thought I was facing was getting Twisted to accept Java's TLS connection which keeps getting rejected for some reason. I read your [TLS support explanation](https://github.com/Syncplay/syncplay/wiki/TLS-support) on the official GitHub. Android's SSL socketing protocol is a pain in the ass and I kept blaming it while I totally forgot to send a TLS message to begin with. I should've analyzed the Python source code more thoroughly to make sure I am not missing anything. That will be immensely helpful to fix this issue. Much appreciated.

**Comment by yuroyami** [comment]
Fixed as of [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0)
