### ISSUE TITLE
Videos showing only black screen unless I enable gpu-next option in 0.13.0 version

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#85]

**Comment by yuroyami** [comment]
I was not able to identify the root of the issue so I will just assume that mpv-android changed some of the defaults arguments passed to mpv after integrating the libplacebo library. I made gpu-next the default option in [v0.14.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.14.0), since there should be no performance overhead or side effects, so I've seen.
