### ISSUE TITLE
Current engine shows `Undefined` and crashes when clicked

### ISSUE THREAD

**Issue by ivy-reps** [yuroyami/syncplay-mobile#97]
No options Just `Reset Default Settings` command. That's all. In my case I was hoping to switch to MPV because when I saw Exoplayer button in options, I immediately decided to switch that on MPV. So I went Advanced and boom Just `Reset Default Settings`  there. Nothing more.

Also is that okay that `Current engine` equals `Undefined`? Or that word means that user have to select player? Also when I'm pressing **SECOND** player to select `Current engine`, program immediately crashes.

https://github.com/yuroyami/syncplay-mobile/assets/102535170/b17bb34a-9ae1-4ec2-a447-431a24839631

**Comment by yuroyami** [comment]
> Also is that okay that Current engine equals Undefined? Or that word means that user have to select player? Also when I'm pressing SECOND player to select Current engine, program immediately crashes.

@ivy-reps `mpv` should be the default engine when available (it's selected by default) otherwise it would be ExoPlayer, so the app should never show "Undefined". This is also directly related to the crash. Thank you for reporting this. By the way, I've noticed that the app icon belongs to an old version, maybe 0.10.0 or 0.11.0 if I am not wrong. Did you install 0.14.0 over the old version ? Maybe that's what's causing the issue.

> No options Just Reset Default Settings command. That's all. In my case I was hoping to switch to MPV because when I saw Exoplayer button in options, I immediately decided to switch that on MPV. So I went Advanced and boom Just Reset Default Settings there. Nothing more.

The "Advanced" settings are supposed to contain miscellaneous settings but I could not think of anything, just the one single setting that resets everything, so this is definitely the intended behavior until I can think of some peculiar settings to put in there.

**Comment by yuroyami** [comment]
In order to avoid this issue, please perform a clean install for the app (which means you uninstall the old version and install the new, this will result in a fresh clean install).
